import aegisIdlJson from "./aegis.json";

export type { Aegis } from "./aegis";
import type { Aegis } from "./aegis";

/** Raw Anchor IDL generated by `NO_DNA=1 anchor build` in `/aegis`. */
export const AEGIS_IDL_JSON = aegisIdlJson;

/** The generated camelCase Anchor TS interface used by client code. */
export type AegisIdl = Aegis;

export type AegisInstruction = Aegis["instructions"][number];
export type AegisInstructionName = AegisInstruction["name"];

